apiVersion: apps/v1
kind: Deployment
metadata:
  name: smi-adapter-maesh
  namespace: maesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smi-adapter-maesh
  template:
    metadata:
      labels:
        name: smi-adapter-maesh
      annotations:
        sidecar.maesh.io/inject: "false"
    spec:
      serviceAccountName: smi-adapter-maesh
      containers:
        - name: smi-adapter-maesh
          image: layer5/smi-maesh:latest
          command:
          - smi-adapter-maesh
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smi-adapter-maesh"
