name: Slack Notify on Star
on: watch
jobs:
  star-notify:
    name: Notify Slack on star
    runs-on: ubuntu-latest
    steps:
    - name: Get current star count
      run: |
        echo "STARS=$(curl --silent 'https://api.github.com/repos/meshery/meshery-traefik-mesh' -H 'Accept: application/vnd.github.preview' | jq '.stargazers_count')" >> $GITHUB_ENV
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CSK7N9TGX\",\"text\":\"Someone just starred Meshery Adapter for Traefik Mesh! (https://github.com/meshery/meshery-traefik-mesh/stargazers) Total ⭐️: ${{env.STARS}}\"}'